MonTPTest/Models/DetailsViewModel.cs
namespace MonTPTest.Models
{
    public class DetailsViewModel
    {
        public CarteGraphique? Carte { get; set; }
        public bool? EstFavoris { get; set; } // Extra :3
        public DetailsViewModel(CarteGraphique? carte, bool? estFavoris)
        {
            Carte = carte;
            EstFavoris = estFavoris;
        }
    }
}

MonTPTest/Controllers/EnfantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Diagnostics;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.Extensions.Primitives;
using MonTPTest.Models;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Drawing.Text;
using System.Net.NetworkInformation;
using Microsoft.AspNetCore.Http;
using MonTPTest.Extensions;
using System.Linq;

namespace MonTPTest.Controllers
{
    public class EnfantController : Controller
    {
        private BaseDonnees m_baseDonnees;
        public EnfantController(BaseDonnees baseDonnees)
        {
            this.m_baseDonnees = baseDonnees;
        }
        

        public IActionResult Recherche(string ?id)
        {   
            string MotCle = "";
            int? Min = null;
            int? Max = null;
            string estVedette = "any";
            bool[] marque = { false, false, false };

                var queries = Request.Query.ToList();
                List<CarteGraphique> mesCartes = m_baseDonnees.Cartes.ToList();
                List<string> marques = new List<string> { };
                //var marquesQuery = queries.Find((query) => query.Key == "marque");
                //var queryMarque = queries.Find((query) => query.Key == "marque");
            queries.ForEach((query) =>
            {
                //Console.WriteLine("Query: " + query.Key.ToString() + " Value: " + query.Value.ToString());
                switch (query.Key)
                {
                    case "marque":
                        query.Value.ToList<string>().ForEach(value => {
                            
                            MarqueDeCarte? oMarque = m_baseDonnees.Marques.Find((MarqueDeCarte oMarque) => { return oMarque.Nom.ToUpper() == value.ToUpper(); });
                            if(marque != null)
                            {
                                #pragma warning disable CS8602 // Dereference of a possibly null reference.
                                int idDeMarque = oMarque.Id -1;
                                #pragma warning restore CS8602 // Dereference of a possibly null reference.
                                marque[idDeMarque] = true;
                                marques.Add(value.ToUpper());
                            }
                            
                        });
                        break;
                    case "marque1":
                        marque[0] = true;
                        marques.Add("NVIDIA");
                        break;
                    case "marque2":
                        marque[1] = true;
                        marques.Add("AMD");
                        break;
                    case "marque3":
                        marque[2] = true;
                        marques.Add("INTEL");
                        break;
                    case "motcle":
                        MotCle = query.Value;
                        break;
                    case "min":
                        Min = int.Parse(query.Value);
                        break;
                    case "max":
                        Max = int.Parse(query.Value);
                        break;
                    case "estvedette":
                        estVedette = query.Value;
                        break;

                }
            });
            if(marques.Count == 0)
            {
                m_baseDonnees.Marques.ForEach((MarqueDeCarte oMarque) => {
                    marques.Add(oMarque.Nom.ToUpper());
                    for(int i = 0; i < marque.Length; i++)
                    {
                        marque[i] = true;
                    }
                });
            }
            ViewDataRecherche data = new ViewDataRecherche(
                filter(m_baseDonnees.Cartes.ToList(), marques, estVedette, Min, Max, MotCle),
                m_baseDonnees.Marques, MotCle, Min, Max, estVedette, marque);
            return View("Recherche", data);
            

        }

        [HttpPost]
        public IActionResult Recherche(IFormCollection collection)
        {
            Func<IFormCollection, string, string> getKey = (IFormCollection col, string key) =>
            {
                return col.ToList().Find(item => { return item.Key == key; }).Value[0].ToString();
            };
            /*StringValues hell = new string[] { "fuck" };
            
            collection.TryGetValue("estVedette", out hell);*/
            collection.ToList().ForEach(item => Console.WriteLine("Item: " + item.Key + "  | Value: " + item.Value[0]));
            //Console.WriteLine(id == null ? "id was null" : "id was not null");
            string MotCle = getKey(collection, "MotCle");

            int? Min = null;
            try { 
                Min = int.Parse(getKey(collection, "Min"));
            }
            catch (Exception)
            {
                Min = null;
            }
            
            int? Max = null;
            try
            {
                Max = int.Parse(getKey(collection, "Max"));
            }
            catch (Exception)
            {
                Max = null;
            }
            string estVedette = getKey(collection, "estVedette");
            List<string> marques = new List<string> { };
            bool[] marque = { bool.Parse(getKey(collection, "marqueNvidia")), bool.Parse(getKey(collection, "marqueAMD")), bool.Parse(getKey(collection, "marqueIntel")) };
            if (marque[0])
            {
                marques.Add("NVIDIA");
            }
            if (marque[1])
            {
                marques.Add("AMD");
            }
            if (marque[2])
            {
                marques.Add("INTEL");
            }
            ViewDataRecherche data = new ViewDataRecherche(
                filter(m_baseDonnees.Cartes.ToList(), marques, estVedette, Min, Max, MotCle),
                m_baseDonnees.Marques, MotCle, Min, Max, estVedette, marque);
            return View("Recherche", data);


        }
        public List<CarteGraphique> filter(List<CarteGraphique> pCartesAFilter, List<string> pMarques, string pEstVedette, int? pMin, int? pMax, string pMotCle)
        {
            Func<CarteGraphique, bool> FiltreMarques = (CarteGraphique pCarte) =>
            {
                return pMarques.Contains(pCarte.Marque.Nom.ToUpper());
            };
            Func<CarteGraphique, bool> FiltreEstVedette = (CarteGraphique pCarte) =>
            {
                return pEstVedette == "yes" ? pCarte.EstVedette : (pEstVedette == "no" ? !pCarte.EstVedette : true);
                /* La ligne ci-dessus équivaut à:
                if (pEstVedette == "yes")
                {
                    return pCarte.EstVedette;
                }
                else if (pEstVedette == "no")
                {
                    return !pCarte.EstVedette;
                }
                else
                {
                    return true;
                }*/
            };
            Func<CarteGraphique, bool> FiltreMin = (CarteGraphique pCarte) =>
            {
                if(pMin == null)
                {
                    return true;
                }
                bool VRAM_CHECK = true;
                StatistiqueString? VRAM = pCarte.Statistiques.Find((StatistiqueString stat) => { return stat.Nom == "VRAM"; });
                if (VRAM != null)
                {
                    decimal Value = decimal.Parse(VRAM.Valeur.Replace("GB",""));
                    if((decimal)pMin > Value)
                    {
                        VRAM_CHECK = false;
                    }
                }
                else
                {
                    VRAM_CHECK = false;
                }
                bool BANDWITH_CHECK = true;
                return VRAM_CHECK && BANDWITH_CHECK;
            };
            Func<CarteGraphique, bool> FiltreMax = (CarteGraphique pCarte) =>
            {
                if (pMax == null)
                {
                    return true;
                }
                bool VRAM_CHECK = true;
                StatistiqueString? VRAM = pCarte.Statistiques.Find((StatistiqueString stat) => { return stat.Nom == "VRAM"; });
                if (VRAM != null)
                {
                    decimal Value = decimal.Parse(VRAM.Valeur.Replace("GB", ""));
                    if ((decimal)pMax < Value)
                    {
                        VRAM_CHECK = false;
                    }
                }
                else
                {
                    VRAM_CHECK = false;
                }
                bool BANDWITH_CHECK = true;
                return VRAM_CHECK && BANDWITH_CHECK;
            };
            Func<CarteGraphique, bool> FiltreMotCle = (CarteGraphique pCarte) =>
            {
                return pCarte.Description.ToUpper().Contains(pMotCle.ToUpper())
                    || pCarte.Nom.Contains(pMotCle.ToUpper()) 
                    || StatistiqueString.Contains(pCarte.Statistiques, pMotCle.ToUpper());
            };
            return pCartesAFilter.Where(FiltreMarques).ToList()
                .Where(FiltreEstVedette).ToList()
                .Where(FiltreMin).ToList()
                .Where(FiltreMax).ToList()
                .Where(FiltreMotCle).ToList();
        }


        public IActionResult Details(string id)
        {
            bool EstFav = false;
            var enfantIDs = HttpContext.Session.Get<List<int>>("enfantsIDs");
            try
            {
                if (enfantIDs != null)
                {
                    if (enfantIDs.Contains(m_baseDonnees.TrouverCarte(id).Id))
                    {
                        EstFav = true;
                    }
                }
            }catch(Exception e)
            {

            }
            return View("Details", new DetailsViewModel(m_baseDonnees.TrouverCarte(id), EstFav));
        }
    }
}

MonTPTest/Controllers/FavorisController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MonTPTest.Extensions;
using MonTPTest.Models;

namespace MonTPTest.Controllers
{
    public class FavorisController : Controller
    {
        private BaseDonnees m_baseDonnees;
        public FavorisController(BaseDonnees baseDonnees)
        {
            this.m_baseDonnees = baseDonnees;
        }
        public IActionResult Index()
        {
            var enfantIDs = HttpContext.Session.Get<List<int>>("enfantsIDs");
            if (enfantIDs == null)
            {
                enfantIDs = new List<int>();
            }
            return View(m_baseDonnees.ObtenirFavoris(enfantIDs));
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AjouterUnFavoris(string id, IFormCollection collection)
        {
            Func<IFormCollection, string, string> getKey = (IFormCollection col, string key) =>
            {
                return col.ToList().Find(item => { return item.Key == key; }).Value[0].ToString();
            };
            var enfantIDs = HttpContext.Session.Get<List<int>>("enfantsIDs");
            if (enfantIDs == null)
            {
                enfantIDs = new List<int>();
            }
            try
            {
                enfantIDs.Add(int.Parse(getKey(collection, "id")));
                HttpContext.Session.Set<List<int>>("enfantsIDs", enfantIDs);
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                return RedirectToAction("Index", "Enfant");
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult RetirerUnFavoris(string id, IFormCollection collection)
        {
            Func<IFormCollection, string, string> getKey = (IFormCollection col, string key) =>
            {
                return col.ToList().Find(item => { return item.Key == key; }).Value[0].ToString();
            };
            
            var enfantIDs = HttpContext.Session.Get<List<int>>("enfantsIDs");
            if (enfantIDs == null)
            {
                enfantIDs = new List<int>();
            }
            try
            {
                enfantIDs.Remove(int.Parse(getKey(collection, "id")));
                HttpContext.Session.Set<List<int>>("enfantsIDs", enfantIDs);
                return RedirectToAction("Index");
            }
            catch(Exception e)
            {
                return RedirectToAction("Index", "Enfant");
            }
            
        }
    }
}

MonTPTest/Views/Enfant/Details.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@Model MonTPTest.Models.DetailsViewModel
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@section title {
    <title>Détails</title>
}
<body id="details">
    @if (Model != null && Model.Carte != null)
    {
        <main id="infoCarte" marque-carte="@Model.Carte.Marque.Nom" class="container" custom-border rounded-corners fill-background>
            <div class="row">
                <div class="col-12">
                    <h1 id="nomCarte">@Model.Carte.Nom</h1>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 col-sm-12">
                    <img class="img-fluid" src="@Model.Carte.ImageCarte" alt="@Model.Carte.ToString()" custom-border rounded-corners fill-background />
                </div>
                <div class="col-spacer col-12 d-md-none"></div>
                <div class="col-md-5 col-sm-6 fuckBootstrap info-labels">
                    <ul class="noMarker">
                        <li>Marque</li>
                        @foreach (StatistiqueString Statistque in Model.Carte.Statistiques)
                        {
                            <li>@Statistque.Nom</li>
                        }
                        <!--<li>VRAM</li>
                        <li>Type de VRAM</li>
                        <li>Coeurs gpu</li>
                        <li>TDP</li>-->
                    </ul>
                </div>
                <div class="col-md-5 col-sm-6 fuckBootstrap card-info">
                    <ul class="noMarker">
                        <li>@Model.Carte.Marque.Nom</li>
                        @foreach (StatistiqueString Statistque in Model.Carte.Statistiques)
                        {
                            <li>@Statistque.Valeur</li>
                        }
                        <!--<li>Q_VRAM</li>
                        <li>TYPE_DE_VRAM</li>
                        <li>NB_COEURS_GPU</li>
                        <li>TDP_W</li>-->
                    </ul>
                </div>
            </div>
            @if (Model.Carte.EstVedette)
            {
                <div class="row">
                    <div class="col-md-2 col-sm-12">
                        <h2><span class="badge bg-secondary">Carte Vedette</span></h2>
                    </div>
                </div>
            }
            <div class="row">
            <div class="col-md-2 col-sm-12">
                    @if (!Model.EstFavoris)
                    {
                        <form asp-controller="Favoris" asp-action="AjouterUnFavoris" class="row justify-content-around" method="POST">
                            <input type="text" hidden name="id" value="@(Model.Carte.Id)">
                        <div class="col-1"></div>
                        <div class="col-10">
                            <div class="row justify-content-between">
                                <button class="col-auto" type="submit" value="Favoris" fill-background rounded-corners rounded-corners-padding-small><i class="fa-solid fa-star"></i> Ajouter aux favoris?</button>
                            </div>
                            <br />
                        </div>
                    </form>}
                    else{
                        <form asp-controller="Favoris" asp-action="RetirerUnFavoris" class="row justify-content-around" method="POST">
                            <input type="text" hidden name="id" value="@(Model.Carte.Id)">
                            <div class="col-1"></div>
                            <div class="col-10">
                                <div class="row justify-content-between">
                                    <button class="col-auto" type="submit" value="Favoris" fill-background rounded-corners rounded-corners-padding-small><i class="fa-solid fa-star"></i> Retirer des favoris?</button>
                                </div>
                                <br />
                            </div>
                        </form>
                    }
            </div>
        </div>
        <div class="row">
            <div class="col-12 description-carte">
                <h2>Description</h2>
                <p>Paragraphe de description sur la carte @Model.Carte.Nom: @Model.Carte.Description</p>
            </div>
        </div>
    </main>
    }
    else{
        <main id="infoCarte" marque-carte="Unknown" class="container" custom-border rounded-corners fill-background>
            <div class="row">
                <div class="col-12">
                    <h1 id="nomCarte">Error 404. Carte non trouvée.</h1>
                </div>
            </div>
        </main>
    }

    </body>

MonTPTest/Views/Enfant/Recherche.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model MonTPTest.Models.ViewDataRecherche
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@section title {
    <title>Recherche</title>
}
<body>
    <main class="container" custom-border fill-background rounded-corners>
        <div class="row">
            <div class="col-12">
                <h1>Liste des cartes graphiques</h1>
            </div>
        </div>
        <div class="row">
            @if (Model.Cartes.Count != 0)
            {
                <div id="liste-des-cartes" class="col-12 col-md-9 order-1 order-md-0">
                    <div class="row cartes">
                        @foreach (CarteGraphique Carte in Model.Cartes)
                        {
                            <partial name="_CartePartial" for="@Carte"/>
                            /*<a href="@Url.Action("Details", "Carte", new { id = Carte.Nom.ToUpper()})" class="col-sm-12 col-md-4">
                                <div class="carte" marque-carte="@(Carte.Marque.Nom)" nom-carte="@(Carte.Nom.ToUpper())" custom-border rounded-corners>
                                    <img class="img-fluid" src="@(Carte.ImageCarte)" alt="@(Carte.ToStringForView())" />
                                </div>
                            </a>*/
                        }
                    </div>
                </div>
            }
            else{
                <div id="liste-des-cartes" class="col-12 col-md-9 order-1 order-md-0">
                    <div class="row cartes">
                        <p class="error404">Error 404... Pas de cartes trouvées...</p>
                    </div>
                </div>
            }
            <div id="form-de-recherche" class="col-12 col-md-3 order-0 order-md-1">
                <p>Le form des cartes</p>
                <form asp-controller="Enfant" asp-action="Recherche" method="post">
                    <div class="col-12">
                        <div class="row">
                            <label asp-for="MotCle"></label>
                            <input type="text" asp-for="MotCle" placeholder="Mot-clé..." fill-background rounded-corners rounded-corners-padding-small />
                        </div>
                        <div class="row justify-content-between">
                            <label asp-for="Min"></label>
                            <input type="number" asp-for="Min" class="col-5" fill-background rounded-corners rounded-corners-padding-small />
                            <input type="number" asp-for="Max" class="col-5" fill-background rounded-corners rounded-corners-padding-small />
                        </div>
                        <div class="row justify-content-between">
                            <label asp-for="estVedette"></label>
                            <select asp-for="estVedette" asp-items="Model.estVedetteItems" fill-background rounded-corners rounded-corners-padding-small></select>
                            
                        </div>
                        <div class="row justify-content-between">
                            <div class="col-12">
                                <label asp-for="marques"></label>
                            </div>
                        </div>
                        <div class="row justify-content-between">
                            <div class="col-12">
                                <input type="checkbox" asp-for="marqueNvidia" fill-background rounded-corners rounded-corners-padding-small />
                                <label asp-for="marqueNvidia"></label>
                            </div>
                            <div class="col-12">
                                <input type="checkbox" asp-for="marqueAMD" fill-background rounded-corners rounded-corners-padding-small />
                                <label asp-for="marqueAMD"></label>
                            </div>
                            <div class="col-12">
                                <input type="checkbox" asp-for="marqueIntel" fill-background rounded-corners rounded-corners-padding-small />
                                <label asp-for="marqueIntel"></label>
                            </div>
                        </div>
                        <div class="row justify-content-between">
                            <button class="col-auto" type="button" title="ResetForm" onclick="resetForm();" fill-background rounded-corners rounded-corners-padding-small>Réinitialiser</button>
                            <input class="col-auto" type="submit" value="Rechercher" fill-background rounded-corners rounded-corners-padding-small />
                        </div>
                        <br />
                    </div>
                </form>
            </div>
        </div>
    </main>
    <script type="text/javascript">
        function resetForm() {
            var form = document.querySelector("#searchForm");
            form.querySelectorAll("input").forEach((inputField) => {
                if (inputField.type == "button" || inputField.type == "submit") {
                    return;
                } else if (inputField.type == "checkbox") {
                    inputField.checked = true;
                } else if (inputField.type == "text") {
                    inputField.value = "";
                } else if (inputField.type == "number") {
                    inputField.value = "";
                }
            });
            form.querySelectorAll("select").forEach((inputField) => {
                inputField.options.selectedIndex = 0;
            });
            editPage();
        }
    </script>
</body>

MonTPTest/Views/Enfant/_CartePartial.cshtml
@using MonTPTest.Models
@model MonTPTest.Models.CarteGraphique
@if (Model != null)
{
    <div class="col-sm-12 col-md-4 uneCarte" marque-carte="@(Model.Marque.Nom)">
        <a href="@Url.Action("Details", "Enfant", new { id = Model.Nom.ToUpper()})" class="col-sm-12 col-md-4 cartea">
            <div class="carte" marque-carte="@(Model.Marque.Nom)" nom-carte="@(Model.Nom.ToUpper())" custom-border rounded-corners>
                <img class="img-fluid" src="@(Model.ImageCarte)" alt="@(Model.ToStringForView())">
            </div>
        </a>
        <div class="overlayDelete">
            <a href="@Url.Action("Delete", "Editor", new { id = Model.Nom.ToUpper()})">
                &nbsp;&nbsp;&nbsp;<i class="fa-regular fa-trash-can"></i>&nbsp;&nbsp;&nbsp;
            </a>
        </div>
    </div>

}
else{
    <a href="" class="col-sm-12 col-md-4">
        <div class="carte" marque-carte="Error" nom-carte="Error" custom-border rounded-corners>
            <img class="img-fluid" src="/images/cartes/error/error.png" alt="Error" />
        </div>
    </a>
}